# Generated by Django 4.0.4 on 2022-04-26 17:27

from asyncio.windows_events import NULL
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
